# Generated by Django 4.2.7 on 2023-11-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='username',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
