# Generated by Django 4.2.7 on 2023-11-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_record_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='record',
            name='username',
            field=models.CharField(default='mune', max_length=100),
            preserve_default=False,
        ),
    ]
