# Generated by Django 4.2.7 on 2023-11-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_record_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='username',
        ),
    ]
